# Generated by Django 4.1.3 on 2023-01-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_profile_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(default=""),
        ),
    ]
