name: react

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node dependencies
        run: cd frontend && npm ci
      - name: Run React tests
        run: cd frontend && npm test -- --coverage .
