name: Python package

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=79 --statistics
      - name: Run Django tests
        run: |
          coverage run manage.py test
      - name: Produce a coverage report
        run: |
          coverage report --fail-under=100
